// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.example.proto;

public interface UploadVideoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.UploadVideoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string url = 3;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>int32 duration_seconds = 4;</code>
   * @return The durationSeconds.
   */
  int getDurationSeconds();

  /**
   * <code>.org.example.proto.Creator creator = 5;</code>
   * @return Whether the creator field is set.
   */
  boolean hasCreator();
  /**
   * <code>.org.example.proto.Creator creator = 5;</code>
   * @return The creator.
   */
  org.example.proto.Creator getCreator();
  /**
   * <code>.org.example.proto.Creator creator = 5;</code>
   */
  org.example.proto.CreatorOrBuilder getCreatorOrBuilder();
}
