// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.example.proto;

public interface VideoStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.VideoStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.proto.Video videos = 1;</code>
   */
  java.util.List<org.example.proto.Video> 
      getVideosList();
  /**
   * <code>repeated .org.example.proto.Video videos = 1;</code>
   */
  org.example.proto.Video getVideos(int index);
  /**
   * <code>repeated .org.example.proto.Video videos = 1;</code>
   */
  int getVideosCount();
  /**
   * <code>repeated .org.example.proto.Video videos = 1;</code>
   */
  java.util.List<? extends org.example.proto.VideoOrBuilder> 
      getVideosOrBuilderList();
  /**
   * <code>repeated .org.example.proto.Video videos = 1;</code>
   */
  org.example.proto.VideoOrBuilder getVideosOrBuilder(
      int index);
}
