// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.example.proto;

public interface VideoIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.VideoIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
